# Generated by Django 2.0.4 on 2018-05-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accountaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addressverify',
            name='address',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='currencypair',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currencypair',
            name='reciprocal_currency',
        ),
        migrations.RemoveField(
            model_name='currencypairrate',
            name='currency_pair',
        ),
        migrations.RemoveField(
            model_name='currencypairrate',
            name='reciprocal_currency',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='application',
        ),
        migrations.RemoveField(
            model_name='systemevents',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountAddress',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressVerify',
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CurrencyPair',
        ),
        migrations.DeleteModel(
            name='CurrencyPairRate',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='SystemEvents',
        ),
    ]
