# Generated by Django 2.0.4 on 2018-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exchanger_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
