# Generated by Django 2.0.4 on 2018-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_exchanger_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='onfido_applicant_id',
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
