# Generated by Django 2.0.4 on 2018-05-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_currency_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingtransaction',
            name='from_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='incomingtransaction',
            name='to_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='transaction_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
