# Generated by Django 2.0.4 on 2018-05-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_fields_into_incoming_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingtransaction',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_txs', to='api.Application'),
        ),
    ]
