# Generated by Django 2.0.4 on 2018-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_incoming_tx_field_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
