# Generated by Django 2.0.4 on 2018-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180608_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
