# Generated by Django 2.0.4 on 2018-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_incoming_tx_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='round_digits',
            field=models.IntegerField(default=8),
        ),
    ]
