# Generated by Django 2.0.4 on 2018-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_currency_round_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='max_limit',
            field=models.FloatField(default=999999999.0),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
