# Generated by Django 2.0.4 on 2018-06-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingtransaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_transactions', to='api.Currency'),
        ),
    ]
