# Generated by Django 2.0.4 on 2018-06-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_incomingtransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges', to='api.Currency'),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refunds', to='api.Currency'),
        ),
    ]
