# Generated by Django 2.0.4 on 2018-06-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180620_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('domicile_country', models.CharField(blank=True, max_length=120)),
                ('business_phone', models.CharField(blank=True, max_length=120)),
                ('business_email', models.EmailField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('apartment', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('asstets_origin', models.CharField(blank=True, max_length=255)),
                ('currency_nature', models.CharField(blank=True, max_length=255)),
                ('asstets_origin_description', models.CharField(blank=True, max_length=255)),
                ('jcash_use', models.CharField(blank=True, max_length=255)),
                ('contact_fullname', models.CharField(blank=True, max_length=255)),
                ('contact_birthday', models.DateField(blank=True, null=True)),
                ('contact_nationality', models.CharField(blank=True, max_length=120)),
                ('contact_residency', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.CharField(blank=True, max_length=120)),
                ('contact_street', models.CharField(blank=True, max_length=120)),
                ('contact_apartment', models.CharField(blank=True, max_length=120)),
                ('contact_city', models.CharField(blank=True, max_length=120)),
                ('contact_postcode', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=120, verbose_name='Country name')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Removed')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('apartment', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('income_source', models.CharField(blank=True, max_length=255)),
                ('asstets_origin', models.CharField(blank=True, max_length=255)),
                ('jcash_use', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personal',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal', to='api.Account'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate', to='api.Account'),
        ),
        migrations.AddField(
            model_name='document',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='api.Personal'),
        ),
    ]
