# Generated by Django 2.0.4 on 2018-06-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_fill_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='api.Corporate'),
        ),
    ]
