# Generated by Django 2.0.4 on 2018-06-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180627_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='personal',
        ),
        migrations.AddField(
            model_name='document',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents',
                                    to='api.Corporate'),
        ),
        migrations.AddField(
            model_name='document',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents',
                                    to='api.Personal'),
        ),
    ]
