# Generated by Django 2.0.4 on 2018-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180629_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
