# Generated by Django 2.0.4 on 2018-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180702_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('mined_at', models.DateTimeField(blank=True, null=True)),
                ('block_height', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'replenisher',
            },
        ),
    ]
