# Generated by Django 2.0.4 on 2018-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_replenisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenisher',
            name='type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
