# Generated by Django 2.0.4 on 2018-07-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_documentverification_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporate',
            old_name='asstets_origin',
            new_name='assets_origin',
        ),
        migrations.RenameField(
            model_name='corporate',
            old_name='asstets_origin_description',
            new_name='assets_origin_description',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='asstets_origin',
            new_name='assets_origin',
        ),
    ]
