# Generated by Django 2.0.4 on 2018-07-28 17:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_auto_20180726_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_remove_license', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenseaddress', to='api.Address')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenseusers', to='api.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenseaddress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licenseuser',
            },
        ),
    ]
