# Generated by Django 2.0.4 on 2018-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_licenseaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
