# Generated by Django 2.0.4 on 2018-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180729_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='base_amount_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='reciprocal_amount_actual',
            field=models.FloatField(default=0.0),
        ),
    ]
