# Generated by Django 2.0.4 on 2018-08-01 07:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180731_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
