# Generated by Django 2.0.4 on 2018-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_documentverification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='is_identity_declined',
            field=models.BooleanField(default=False, verbose_name='Declined'),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='is_identity_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
