# Generated by Django 2.0.4 on 2018-08-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180801_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='onfido_applicant_id',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='onfido_applicant_id',
        ),
        migrations.AddField(
            model_name='corporate',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
