# Generated by Django 2.0.4 on 2018-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180802_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='onfido_check_created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='onfido_check_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='onfido_check_result',
        ),
        migrations.RemoveField(
            model_name='document',
            name='onfido_check_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='onfido_document_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verification_started_at',
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_check_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_check_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_check_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_check_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_passport_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_selfie_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='onfido_utilitybills_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='verification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
