# Generated by Django 2.0.4 on 2018-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180802_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='is_applicant_changed',
            field=models.BooleanField(default=False),
        ),
    ]
