# Generated by Django 2.0.4 on 2018-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_documentverification_is_applicant_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentverification',
            name='onfido_passport_id',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='onfido_selfie_id',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='onfido_utilitybills_id',
        ),
        migrations.AddField(
            model_name='document',
            name='onfido_document_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
