# Generated by Django 2.0.4 on 2018-08-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180802_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='email',
        ),
    ]
