# Generated by Django 2.0.4 on 2018-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_documentverification_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemevents',
            name='user',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='account_type_07a27f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='account_created_f8eca1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['last_updated_at'], name='account_last_up_633cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_identity_verified'], name='account_is_iden_7d9331_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_identity_declined'], name='account_is_iden_155f06_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_blocked'], name='account_is_bloc_75b696_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address'], name='address_address_b4365f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['type'], name='address_type_3c9ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_verified'], name='address_is_veri_7c6cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_rejected'], name='address_is_reje_82ab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_removed'], name='address_is_remo_4a4de1_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_allowed'], name='address_is_allo_302c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['created_at'], name='address_created_4648ff_idx'),
        ),
        migrations.AddIndex(
            model_name='addressverify',
            index=models.Index(fields=['created_at'], name='address_ver_created_ab3bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='addressverify',
            index=models.Index(fields=['is_verified'], name='address_ver_is_veri_99416a_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['event'], name='affiliate_event_f21809_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['url'], name='affiliate_url_9acd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['created'], name='affiliate_created_22ab44_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['sended'], name='affiliate_sended_cebe10_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['status'], name='affiliate_status_e708cb_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['exchanger_address'], name='application_exchang_39356b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['base_currency'], name='application_base_cu_ff3e34_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reciprocal_currency'], name='application_recipro_97d5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['base_amount_actual'], name='application_base_am_e3b364_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reciprocal_amount_actual'], name='application_recipro_13f353_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_75d36c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['expired_at'], name='application_expired_2078dc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_active'], name='application_is_acti_69494f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_reverse'], name='application_is_reve_5a2efe_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_b7b725_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['country'], name='api_corpora_country_704b10_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['city'], name='api_corpora_city_64082f_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['industry'], name='api_corpora_industr_8b5b89_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['jcash_use'], name='api_corpora_jcash_u_fa35eb_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['name'], name='api_corpora_name_565535_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['created_at'], name='api_corpora_created_38cd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['last_updated_at'], name='api_corpora_last_up_4c8a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['status'], name='api_corpora_status_e26395_idx'),
        ),
        migrations.AddIndex(
            model_name='corporate',
            index=models.Index(fields=['onfido_applicant_id'], name='api_corpora_onfido__613722_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['type'], name='api_country_type_b5c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_removed'], name='api_country_is_remo_a750fb_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['display_name'], name='currency_display_20e157_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['symbol'], name='currency_symbol_45f9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['exchanger_address'], name='currency_exchang_8ff5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['view_address'], name='currency_view_ad_36180a_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['controller_address'], name='currency_control_c4e275_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['license_registry_address'], name='currency_license_8193b4_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_erc20_token'], name='currency_is_erc2_1bad88_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['created_at'], name='currency_created_a33d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['display_name'], name='currency_pa_display_d50f39_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['symbol'], name='currency_pa_symbol_c9c3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['is_exchangeable'], name='currency_pa_is_exch_54ed50_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['created_at'], name='currency_pa_created_055899_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['is_buyable'], name='currency_pa_is_buya_354eee_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypair',
            index=models.Index(fields=['is_sellable'], name='currency_pa_is_sell_7e08ef_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypairrate',
            index=models.Index(fields=['created_at'], name='currency_pa_created_5e80e9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ext'], name='document_ext_29aca3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type'], name='document_type_112a60_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['group'], name='document_group_eb6f68_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='document_created_71db36_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['created_at'], name='api_documen_created_1965b3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['status'], name='api_documen_status_32602e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['is_identity_verified'], name='api_documen_is_iden_7dd78f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['is_identity_declined'], name='api_documen_is_iden_47cd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['is_applicant_changed'], name='api_documen_is_appl_e9c6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['onfido_check_id'], name='api_documen_onfido__178fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['onfido_check_status'], name='api_documen_onfido__8daf27_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['onfido_check_result'], name='api_documen_onfido__0e7845_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['onfido_check_created'], name='api_documen_onfido__1499b5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verification_started_at'], name='api_documen_verific_3f01e6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verification_attempts'], name='api_documen_verific_cbec1e_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['transaction_id'], name='exchange_transac_5d27e9_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['created_at'], name='exchange_created_66153f_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['mined_at'], name='exchange_mined_a_b9d37e_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['block_height'], name='exchange_block_h_d090f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['to_address'], name='exchange_to_addr_04fceb_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['value'], name='exchange_value_6f0692_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['status'], name='exchange_status_f71666_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['transaction_id'], name='incoming_tr_transac_9b2567_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['created_at'], name='incoming_tr_created_1b28d8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['mined_at'], name='incoming_tr_mined_a_b73d22_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['block_height'], name='incoming_tr_block_h_39c152_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['from_address'], name='incoming_tr_from_ad_a4c11f_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['to_address'], name='incoming_tr_to_addr_24eee0_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['value'], name='incoming_tr_value_deec63_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['status'], name='incoming_tr_status_2e25e3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['is_linked'], name='incoming_tr_is_link_9d551a_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseaddress',
            index=models.Index(fields=['status'], name='license_add_status_0869e7_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseaddress',
            index=models.Index(fields=['is_remove_license'], name='license_add_is_remo_67d0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseaddress',
            index=models.Index(fields=['created_at'], name='license_add_created_befb14_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notificatio_type_f65c28_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email'], name='notificatio_email_d30e54_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created'], name='notificatio_created_c10353_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sended'], name='notificatio_sended_f801e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sended'], name='notificatio_is_send_89a2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['country'], name='api_persona_country_4f7e67_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['city'], name='api_persona_city_812457_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['profession'], name='api_persona_profess_83aa5c_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['jcash_use'], name='api_persona_jcash_u_e70879_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['income_source'], name='api_persona_income__cac9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['created_at'], name='api_persona_created_30db52_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['last_updated_at'], name='api_persona_last_up_7f4c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['status'], name='api_persona_status_4d5cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['onfido_applicant_id'], name='api_persona_onfido__3551c5_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['transaction_id'], name='refund_transac_3b4b40_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='refund_created_336c34_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['mined_at'], name='refund_mined_a_905b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['block_height'], name='refund_block_h_de3369_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['to_address'], name='refund_to_addr_bd9749_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['value'], name='refund_value_a1c4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='refund_status_1fc04e_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_admin_approved'], name='refund_is_admi_c7c613_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['type'], name='replenisher_type_9961fa_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['mined_at'], name='replenisher_mined_a_9773c5_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['block_height'], name='replenisher_block_h_4c0c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['is_removed'], name='replenisher_is_remo_fdf151_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['created_at'], name='replenisher_created_6c0eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='replenisher',
            index=models.Index(fields=['last_updated_at'], name='replenisher_last_up_1ed969_idx'),
        ),
        migrations.DeleteModel(
            name='AccountAddress',
        ),
        migrations.DeleteModel(
            name='SystemEvents',
        ),
    ]
