# Generated by Django 2.0.4 on 2018-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20180805_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='sort_id',
            field=models.IntegerField(default=0),
        ),
    ]
