# Generated by Django 2.0.4 on 2018-08-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_currencypair_sort_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='version',
        ),
    ]
