# Generated by Django 2.0.4 on 2018-08-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_currency_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_block', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exchange_fee',
            },
        ),
    ]
