# Generated by Django 2.0.4 on 2018-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_exchangefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
    ]
