# Generated by Django 2.0.4 on 2018-08-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_add_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporate',
            old_name='contact_fullname',
            new_name='contact_firstname',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='corporate',
            name='contact_lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corporate',
            name='contact_middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personal',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
