# Generated by Django 2.0.4 on 2018-10-08 06:26

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0063_auto_20180824_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('message', models.CharField(max_length=1024)),
                ('video_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_verification', to='api.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videoverification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_verification',
            },
        ),
        migrations.AddField(
            model_name='documentverification',
            name='video_verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_document_verification', to='api.VideoVerification'),
        ),
        migrations.AddIndex(
            model_name='videoverification',
            index=models.Index(fields=['created_at'], name='video_verif_created_2ab7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='videoverification',
            index=models.Index(fields=['is_verified'], name='video_verif_is_veri_6373c8_idx'),
        ),
    ]
