# Generated by Django 2.0.4 on 2018-10-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20181008_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoverification',
            old_name='file',
            new_name='document',
        ),
    ]
