# Generated by Django 2.0.4 on 2018-10-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20181010_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='api.Corporate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='api.Personal'),
        ),
    ]
