# Generated by Django 2.0.4 on 2018-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20181010_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='is_information_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporate',
            name='is_not_political',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporate',
            name='is_terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporate',
            name='is_ultimate_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporate',
            name='kyc_step',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_information_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_not_political',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_ultimate_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='kyc_step',
            field=models.IntegerField(default=1),
        ),
    ]
