# Generated by Django 2.0.4 on 2018-11-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20181103_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='personal',
        ),
        migrations.AddField(
            model_name='corporate',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_passport', to='api.Document'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='selfie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_selfie', to='api.Document'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='utilitybills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_utilitybills', to='api.Document'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_video', to='api.Document'),
        ),
        migrations.AddField(
            model_name='personal',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_passport', to='api.Document'),
        ),
        migrations.AddField(
            model_name='personal',
            name='selfie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_selfie', to='api.Document'),
        ),
        migrations.AddField(
            model_name='personal',
            name='utilitybills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_utilitybills', to='api.Document'),
        ),
        migrations.AddField(
            model_name='personal',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_video', to='api.Document'),
        ),
    ]
