# Generated by Django 2.0.4 on 2018-11-05 08:03

from django.db import migrations


def remove_USA_country(apps, schema_editor):
    Country = apps.get_model('api', 'Country')

    citizenship = Country.objects\
        .filter(type='citizenship', name='United States of America (USA)')\
        .update(is_removed=True)

    residential = Country.objects\
        .filter(type="residential", name='United States of America') \
        .update(is_removed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20181103_0700'),
    ]

    operations = [
        migrations.RunPython(remove_USA_country)
    ]
