# Generated by Django 2.0.4 on 2018-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_Virgin_Islands_US_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verification_report_available',
            field=models.BooleanField(default=False),
        ),
    ]
