# Generated by Django 2.0.4 on 2018-11-03 07:30

from django.db import migrations, transaction
from django.db.models import Q


def migrate_video_verifications(apps, schema_editor):
    Account = apps.get_model('api', 'Account')
    DocumentVerification = apps.get_model('api', 'DocumentVerification')

    accounts = Account.objects.all()

    with transaction.atomic():
        for account in accounts:
            last_document_verification = None
            try:
                last_document_verification = DocumentVerification.objects\
                    .filter(user=account.user)\
                    .filter(~Q(personal=None) if account.type == 'personal' else ~Q(corporate=None))\
                    .latest('created_at')
            except DocumentVerification.DoesNotExist:
                pass

            if last_document_verification and last_document_verification.report:
                account.is_verification_report_available = True
                account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20181104_1212'),
    ]

    operations = [
        migrations.RunPython(migrate_video_verifications),
    ]
