# Generated by Django 2.0.4 on 2018-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_migrate_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_verification_report_available',
            field=models.BooleanField(default=False, verbose_name='Screened'),
        ),
    ]
